#' Plot of importance value index
#'
#' @param data a tibble containing importance value index generated by function IVI()
#'
#' @return A plot (ggplot) of importance value index and its components, ordered descending
#' @import reshape2
#' @import ggplot2
#' @export
#'
#' @examples
IVI_plot <- function(data){
  melted_data <- reshape2::melt(data[,-5], id = "Species")
  p <- ggplot2::ggplot(melted_data, ggplot2::aes(x = reorder(Species, -value), value, fill = variable)) +
    ggplot2::geom_bar(stat = "identity", position = "stack") +
    ggplot2::xlab("Species") +
    ggplot2::ylab("Importance value index") +
    ggplot2::scale_fill_discrete("Components",
                        labels = c("Frequency", "Density", "Coverage")) +
    ggplot2::theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust=1))
  print(p)
}
